import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "public/mock-sw.js", // generated by scripts/build-sw.mjs
      "test-results/**",
      "playwright-report/**",
    ],
  },
  ...coreWebVitals,
  ...typescript,
  {
    // Lint was introduced by the branch that moved the mock API into the
    // browser, so these files predate it. They are course content that the
    // branch deliberately does not touch, and each violation is a real but
    // separate piece of work. They stay visible as warnings rather than being
    // switched off, so the debt is recorded instead of hidden.
    files: [
      "app/auth/viz.tsx",
      "app/command-palette.tsx",
      "app/home-viz.tsx",
      "app/theme-provider.tsx",
      "lib/i18n.tsx",
      "lib/progress.tsx",
      "lib/quiz.tsx",
      "lib/stepper.tsx",
    ],
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/purity": "warn",
      "react/no-unescaped-entities": "warn",
    },
  },
];

export default config;
