// Bundles the TypeScript Service Worker into public/mock-sw.js.
//
// Next.js does not bundle service workers, and the worker has to share the very
// same engine the server and the tests use -- duplicating that logic in hand
// written JavaScript would guarantee the two copies drift apart. esbuild is a
// build-time dependency only; nothing extra ships to the browser beyond this
// one file.

import { build } from "esbuild";
import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const outfile = path.join(root, "public", "mock-sw.js");

await mkdir(path.join(root, "public"), { recursive: true });

const result = await build({
  entryPoints: [path.join(root, "sw", "mock-sw.ts")],
  outfile,
  bundle: true,
  format: "iife", // classic worker: registered without { type: "module" }
  platform: "browser",
  target: ["chrome111", "firefox111", "safari16.4"],
  minify: process.env.NODE_ENV === "production",
  sourcemap: false,
  legalComments: "none",
  banner: {
    js: "// Generated by scripts/build-sw.mjs from sw/mock-sw.ts. Do not edit by hand.",
  },
  logLevel: "silent",
  metafile: true,
});

const bytes = Object.values(result.metafile.outputs)[0]?.bytes ?? 0;
console.log(`build-sw: public/mock-sw.js (${(bytes / 1024).toFixed(1)} kB)`);
